# production:
#   bucket: landing_page_dev_env-production
#   access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
#   secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
#
# development: &defaults
#   access_key_id: 12342134
#   secret_access_key: 123412341234
#   bucket: landing_page_dev_env-development
#
# test:
#   <<: *defaults
#   bucket: landing_page_dev_env-test
#
# demo:
#   <<: *defaults
#   bucket: landing_page_dev_env-demo
#
# staging:
#   <<: *defaults
#   bucket: landing_page_dev_env-staging
#
# sandbox:
#   <<: *defaults
#   bucket: landing_page_dev_env-sandbox
